// flow-typed signature: 32a718983e166bd89eb06cbebba8599a
// flow-typed version: <<STUB>>/@vx/responsive_v0.0.127/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/responsive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/responsive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/responsive/build/components/ResponsiveSVG' {
  declare module.exports: any;
}

declare module '@vx/responsive/build/components/ScaleSVG' {
  declare module.exports: any;
}

declare module '@vx/responsive/build/enhancers/withParentSize' {
  declare module.exports: any;
}

declare module '@vx/responsive/build/enhancers/withScreenSize' {
  declare module.exports: any;
}

declare module '@vx/responsive/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/responsive/build/components/ResponsiveSVG.js' {
  declare module.exports: $Exports<'@vx/responsive/build/components/ResponsiveSVG'>;
}
declare module '@vx/responsive/build/components/ScaleSVG.js' {
  declare module.exports: $Exports<'@vx/responsive/build/components/ScaleSVG'>;
}
declare module '@vx/responsive/build/enhancers/withParentSize.js' {
  declare module.exports: $Exports<'@vx/responsive/build/enhancers/withParentSize'>;
}
declare module '@vx/responsive/build/enhancers/withScreenSize.js' {
  declare module.exports: $Exports<'@vx/responsive/build/enhancers/withScreenSize'>;
}
declare module '@vx/responsive/build/index.js' {
  declare module.exports: $Exports<'@vx/responsive/build/index'>;
}
